"use client";

import { Brain, CheckCircle2, TrendingUp, TrendingDown, Minus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

export function ReflectionCompletion({ witnessed, causality, nextAction, confidenceAdjustment, onToday, onOverview }: { witnessed?: string; causality?: string; nextAction: string; confidenceAdjustment?: { before: number; after: number; trend: "up" | "down" | "flat" | "unknown" }; onToday: () => void; onOverview: () => void }) {
  const trendIcon = confidenceAdjustment?.trend === "up" ? <TrendingUp size={11} /> : confidenceAdjustment?.trend === "down" ? <TrendingDown size={11} /> : <Minus size={11} />;
  return <div className="mx-auto max-w-[560px] px-3 py-8 text-center sm:px-6 sm:py-10"><div className="mx-auto grid size-14 place-items-center rounded-full border border-[var(--bm-green-bd)] bg-[var(--bm-green-dim)]"><CheckCircle2 size={24} className="text-[var(--bm-green)]" /></div><p className="mt-4 font-mono text-[10px] font-medium uppercase tracking-[0.1em] text-[var(--bm-text3)]">Learning captured</p><h2 className="mt-1 text-[22px] font-bold text-[var(--bm-text)]">Reflection saved</h2><p className="mt-2 text-[13px] leading-relaxed text-[var(--bm-text3)]">Tomorrow&apos;s decision will use what you learned today.</p><div className="mt-6 space-y-3 text-left">{witnessed ? <Card variant="insight" className="rounded-[var(--r-xl)] p-4 text-sm leading-relaxed text-[var(--bm-text)]">{witnessed}</Card> : null}{confidenceAdjustment ? <Card className="rounded-[var(--r-xl)] p-4"><p className="font-mono text-[10px] uppercase tracking-[0.08em] text-[var(--bm-intel)]">Confidence adjustment</p><div className="mt-2 flex items-baseline gap-2"><span className="text-lg font-bold text-[var(--bm-text2)]">{confidenceAdjustment.before}%</span><span className="text-[var(--bm-text4)]">→</span><span className="text-lg font-bold text-[var(--bm-text)]">{confidenceAdjustment.after}%</span><span className="ml-1 flex items-center gap-1 text-[11px] font-medium text-[var(--bm-text3)]">{trendIcon}{confidenceAdjustment.trend === "unknown" ? "" : confidenceAdjustment.trend}</span></div><p className="mt-2 text-[12px] leading-relaxed text-[var(--bm-text3)]">This reflection resolved a pending prediction — BuildMind's rolling accuracy for what it recommends you updated to match.</p></Card> : null}{causality ? <Card variant="insight" className="rounded-[var(--r-xl)] p-4"><p className="flex items-center gap-1.5 font-mono text-[10px] uppercase tracking-[0.08em] text-[var(--bm-intel)]"><Brain size={11} /> What changes next</p><p className="mt-2 text-sm leading-relaxed text-[var(--bm-text2)]">{causality}</p></Card> : null}<Card className="rounded-[var(--r-xl)] p-4"><p className="font-mono text-[10px] uppercase tracking-[0.08em] text-[var(--bm-text3)]">Tomorrow&apos;s focus</p><p className="mt-2 text-sm leading-relaxed text-[var(--bm-text2)]">{nextAction}</p></Card></div><div className="mt-5 flex flex-col gap-2 sm:flex-row"><Button variant="secondary" fullWidth onClick={onOverview}>Back to dashboard</Button><Button fullWidth onClick={onToday}>Back to Today</Button></div></div>;
}
