/**
 * components/MorningBriefingCard.tsx — Playbook §4.1 + §3.2
 *
 * Displays the AI-generated morning briefing (win / risk / action).
 * 3 lines. Generated by the Reflexion loop.
 * Delivered before the founder opens the app via push notification.
 * On open → shown at the top of /today.
 *
 * v2: all colors use design system CSS vars (no hardcoded hex/rgba)
 */
"use client";

import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { fetchMorningBriefing, type MorningBriefing } from "@/lib/founderContext";
import { usePlan } from "@/lib/usePlan";
import { AIErrorBoundary } from "./AIErrorBoundary";

function MorningBriefingCardInner({ initialBriefing }: { initialBriefing?: MorningBriefing | null }) {
  const [briefing, setBriefing] = useState<MorningBriefing | null>(initialBriefing ?? null);
  const [loading, setLoading] = useState(initialBriefing === undefined);
  const [open, setOpen] = useState(true);
  const { plan } = usePlan();

  useEffect(() => {
    if (initialBriefing !== undefined) {
      setBriefing(initialBriefing);
      setLoading(false);
      return;
    }
    fetchMorningBriefing().then(b => { setBriefing(b); setLoading(false); }).catch(() => setLoading(false));
  }, [initialBriefing]);

  if (loading || !briefing || !open) return null;

  const isPaywalled = plan === "free";

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0, y: -8 }}
        animate={{ opacity: 1, y: 0 }}
        exit={{ opacity: 0, y: -8 }}
        style={{
          background: "var(--bm-accent-dim)",
          border: "1px solid var(--bm-accent-bd)",
          borderRadius: "var(--r-lg)",
          padding: "14px 16px",
          marginBottom: 16,
          position: "relative",
        }}
      >
        <button
          onClick={() => setOpen(false)}
          style={{
            position: "absolute", top: 8, right: 10, background: "none", border: "none",
            color: "var(--bm-text4)", cursor: "pointer", fontSize: 14, fontFamily: "inherit",
          }}
        >
          ×
        </button>

        <div style={{
          fontSize: 9, color: "var(--bm-accent)", letterSpacing: "0.1em",
          textTransform: "uppercase", marginBottom: 10, fontWeight: 600,
        }}>
          ⚡ Morning briefing
        </div>

        {isPaywalled ? (
          <div>
            <div style={{ fontSize: 12, color: "var(--bm-text3)", lineHeight: 1.6, marginBottom: 10 }}>
              <span style={{ color: "var(--bm-green)", fontWeight: 600 }}>Win:</span>{" "}
              {briefing.win.slice(0, 40)}…
            </div>
            <div style={{ fontSize: 11, color: "var(--bm-text3)", fontStyle: "italic", marginBottom: 10 }}>
              Your risk and today&apos;s action are in Builder.
            </div>
            <a href="/upgrade" style={{
              display: "inline-block", fontSize: 11, fontWeight: 600,
              color: "var(--bm-accent)",
              background: "var(--bm-accent-dim)",
              border: "1px solid var(--bm-accent-bd)",
              borderRadius: "var(--r-sm)", padding: "5px 12px", textDecoration: "none",
            }}>
              Unlock full briefing — Builder →
            </a>
          </div>
        ) : (
          <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
            <div style={{ display: "flex", gap: 8, alignItems: "flex-start" }}>
              <span style={{ fontSize: 10, color: "var(--bm-green)", fontWeight: 700, minWidth: 38, paddingTop: 1 }}>WIN</span>
              <span style={{ fontSize: 12, color: "var(--bm-text2)", lineHeight: 1.55 }}>{briefing.win}</span>
            </div>
            <div style={{ display: "flex", gap: 8, alignItems: "flex-start" }}>
              <span style={{ fontSize: 10, color: "var(--bm-amber)", fontWeight: 700, minWidth: 38, paddingTop: 1 }}>RISK</span>
              <span style={{ fontSize: 12, color: "var(--bm-text2)", lineHeight: 1.55 }}>{briefing.risk}</span>
            </div>
            <div style={{ display: "flex", gap: 8, alignItems: "flex-start" }}>
              <span style={{ fontSize: 10, color: "var(--bm-accent)", fontWeight: 700, minWidth: 38, paddingTop: 1 }}>NOW</span>
              <span style={{ fontSize: 12, color: "var(--bm-text)", fontWeight: 600, lineHeight: 1.55 }}>{briefing.action}</span>
            </div>
          </div>
        )}
      </motion.div>
    </AnimatePresence>
  );
}

export default function MorningBriefingCard({ initialBriefing }: { initialBriefing?: MorningBriefing | null }) {
  return (
    <AIErrorBoundary feature="Morning Briefing">
      <MorningBriefingCardInner initialBriefing={initialBriefing} />
    </AIErrorBoundary>
  );
}
