/**
 * lib/founderMirror.ts — Phase 9: The Founder Mirror
 *
 * A continuously-evolving, behavior-derived model that answers:
 *   - What does BuildMind currently believe about me?
 *   - Why does it believe it, and what's the evidence?
 *   - How confident is it?
 *   - What changed recently?
 *   - What patterns are strengthening / weakening?
 *   - What might BuildMind be wrong about?
 *
 * Deliberately NOT a personality quiz. Every belief is derived from
 * FounderIntelligenceState, which is itself derived from real behavior
 * (reflections, task outcomes, activity, recommendation acceptance/rejection).
 * No belief is stated without a link back to the evidence that produced it.
 *
 * Consumers: app/api/founder-context/mirror/route.ts, app/founder-mirror/page.tsx.
 *
 * ── Correction feedback loop ────────────────────────────────────────────
 * Founder corrections used to be stored and echoed back but never changed
 * what got generated next time. This version treats a correction the same
 * way lib/founderIntelligence.ts already treats a decision candidate's
 * track record: a Thompson-Sampling-style Beta(successes+1, failures+1)
 * posterior (sampleBeta, imported from lib/founderIntelligence.ts — the
 * exact same primitive, not a second copy of it), sampled per belief, so a
 * correction pulls confidence down probabilistically and DECAYS over time
 * (21-day half-life — longer than a signal's, since a founder correction is
 * a deliberate statement, not an auto-detected pattern) rather than
 * silencing a belief forever. If fresh evidence keeps supporting a
 * corrected belief, it can recover; if corrections keep landing on it, it
 * gets suppressed from the list entirely instead of just cosmetically
 * noted next to it.
 */

import type { FounderIntelligenceState, IntelligenceSignal } from "@/lib/founderIntelligence";
import { sampleBeta, activeSignals } from "@/lib/founderIntelligence";
import type { IntelligenceAccuracy } from "@/lib/learningLoop";
import { buildFounderSkills, type FounderSkill } from "@/lib/founderSkills";

export interface FounderCorrection {
  belief: string;
  correction: string;
  evidence?: string;
  created_at?: string;
  /** Stable key of the specific belief this targets. "general" (or absent)
   *  means it applies to every belief, at reduced weight — see
   *  GENERAL_CORRECTION_WEIGHT below. */
  belief_key?: string;
}

export interface CorrectionEffect {
  corrections_applied: number;
  confidence_before: number;
  confidence_after: number;
}

export interface FounderBelief {
  belief: string;
  belief_key: string;
  why: string;
  evidence: string[];
  confidence: number; // 0-1
  trend: "strengthening" | "weakening" | "persistent" | "emerging";
  last_updated: string;
  contradictory_evidence: string[];
  correction_effect: CorrectionEffect | null;
}

export interface MirrorSignal {
  id: string;
  type: string;
  severity: string;
  title: string;
  summary: string;
  recommended_response: string;
  evidence: Array<{ source: string; detail: string }>;
  decayed_confidence: number;
  lifecycle: string;
}

export interface MirrorDecisionTop {
  id: string;
  action: string;
  rationale: string;
  why_it_beats_alternatives: string;
  score: number;
}

export interface MirrorDecisionAlternative {
  id: string;
  action: string;
  rationale: string;
  score: number;
  gap_to_top: number;
}

export interface FounderMirror {
  beliefs: FounderBelief[];
  skills: FounderSkill[];
  recent_changes: string[];
  strengthening_patterns: string[];
  weakening_patterns: string[];
  may_be_wrong_about: string[];
  signals: MirrorSignal[];
  decision: { top: MirrorDecisionTop | null; alternatives: MirrorDecisionAlternative[] };
  suppressed_beliefs: Array<{ belief: string; reason: string }>;
  self_reported_accuracy: {
    sample_size: number;
    accuracy_pct: number | null;
    trend: IntelligenceAccuracy["trend"];
    summary: string;
  };
  generated_at: string;
}

// ── Belief keying (shared with the correction API route and the page's
// "Correct this" action, so a correction submitted against a specific
// belief's displayed text always resolves to the same key it was
// generated with here) ──────────────────────────────────────────────────
export function normalizeBeliefKey(text: string): string {
  const slug = text
    .toLowerCase()
    // Keep hyphens (not just letters/digits/whitespace) so this is
    // idempotent — normalizeBeliefKey(normalizeBeliefKey(x)) === normalizeBeliefKey(x).
    // That matters: correctionScope() re-normalizes belief_key on every read
    // (defensive against unnormalized historical rows), and a belief's own
    // key is generated by normalizing its raw text exactly once — those two
    // paths must land on the same string for a stored correction to ever
    // match the belief it targeted.
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 80)
    .replace(/^-|-$/g, "");
  return slug || "general";
}

const GENERAL_KEYS = new Set(["general", "general-founder-mirror-model"]);

function correctionScope(c: FounderCorrection): string {
  const key = normalizeBeliefKey(c.belief_key || c.belief || "general");
  return key;
}

// A correction is a deliberate, considered statement — it should outlast an
// auto-detected behavioral signal (10-day half-life in founderIntelligence.ts),
// but still fade if the founder never reinforces it and fresh evidence keeps
// pointing the other way.
const CORRECTION_HALF_LIFE_DAYS = 21;
const GENERAL_CORRECTION_WEIGHT = 0.4;
const SUPPRESSION_THRESHOLD = 0.22;

function decayedCorrectionWeight(createdAt: string | undefined, asOf: Date): number {
  if (!createdAt) return 1;
  const created = new Date(createdAt).getTime();
  if (!Number.isFinite(created)) return 1;
  const daysSince = Math.max(0, (asOf.getTime() - created) / 86_400_000);
  return Math.exp(-Math.LN2 * (daysSince / CORRECTION_HALF_LIFE_DAYS));
}

function clamp01(n: number): number {
  return Math.max(0, Math.min(1, n));
}

interface Weighting {
  confidence: number;
  correctionsApplied: number;
  confidenceBefore: number;
  suppressed: boolean;
}

/**
 * Blends a belief's evidence-derived confidence with a Beta(successes+1,
 * failures+1) posterior sampled the same way scoreCandidate() samples
 * archetype_stats in lib/founderIntelligence.ts. "successes" is the amount
 * of fresh evidence currently backing the belief; "failures" is the
 * decayed weight of corrections that landed on it. A belief with real,
 * decayed-weight corrections against it and a resulting low blended
 * confidence gets suppressed rather than shown with a token confidence bar.
 */
function applyCorrections(
  beliefKey: string,
  baseConfidence: number,
  evidenceCount: number,
  corrections: FounderCorrection[],
  asOf: Date,
): Weighting {
  let failures = 0;
  let matchedCount = 0;
  for (const c of corrections) {
    const scope = correctionScope(c);
    const weight = decayedCorrectionWeight(c.created_at, asOf);
    if (scope === beliefKey) {
      failures += weight;
      matchedCount += 1;
    } else if (GENERAL_KEYS.has(scope)) {
      failures += weight * GENERAL_CORRECTION_WEIGHT;
    }
  }
  if (failures <= 0.05) {
    return { confidence: baseConfidence, correctionsApplied: 0, confidenceBefore: baseConfidence, suppressed: false };
  }
  const successes = Math.max(1, evidenceCount);
  const learned = sampleBeta(successes + 1, failures + 1);
  const confidence = clamp01((baseConfidence + learned) / 2);
  const suppressed = matchedCount > 0 && confidence < SUPPRESSION_THRESHOLD;
  return { confidence, correctionsApplied: matchedCount, confidenceBefore: baseConfidence, suppressed };
}

function correctionTextsFor(beliefKey: string, corrections: FounderCorrection[]): string[] {
  const specific = corrections.filter((c) => correctionScope(c) === beliefKey);
  const general = corrections.filter((c) => GENERAL_KEYS.has(correctionScope(c)));
  const pool = specific.length ? specific : general;
  return pool.slice(-2).map((c) => c.correction);
}

function beliefsFromState(
  state: FounderIntelligenceState,
  asOf: Date,
): { beliefs: FounderBelief[]; suppressed: Array<{ belief: string; reason: string }> } {
  const corrections = state.founder.corrections;
  const beliefs: FounderBelief[] = [];
  const suppressed: Array<{ belief: string; reason: string }> = [];

  function push(text: string, why: string, evidence: string[], baseConfidence: number, trend: FounderBelief["trend"]) {
    const beliefKey = normalizeBeliefKey(text);
    const weighting = applyCorrections(beliefKey, baseConfidence, evidence.length, corrections, asOf);
    if (weighting.suppressed) {
      suppressed.push({
        belief: text,
        reason: `Softened out after ${weighting.correctionsApplied} correction${weighting.correctionsApplied === 1 ? "" : "s"} — confidence dropped to ${Math.round(weighting.confidence * 100)}%.`,
      });
      return;
    }
    beliefs.push({
      belief: text,
      belief_key: beliefKey,
      why,
      evidence,
      confidence: weighting.confidence,
      trend,
      last_updated: state.generated_at,
      contradictory_evidence: correctionTextsFor(beliefKey, corrections),
      correction_effect:
        weighting.correctionsApplied > 0
          ? {
              corrections_applied: weighting.correctionsApplied,
              confidence_before: Math.round(weighting.confidenceBefore * 100) / 100,
              confidence_after: Math.round(weighting.confidence * 100) / 100,
            }
          : null,
    });
  }

  for (const strength of state.founder.strengths.slice(0, 3)) {
    push(
      `You tend to be strong at ${strength}.`,
      "Derived from which recommendation and task types you actually complete, not a self-report.",
      state.execution.completed_actions.slice(0, 3),
      Math.max(0.3, state.founder.confidence / 100),
      state.temporal.strengthening_patterns.length ? "strengthening" : "persistent",
    );
  }

  for (const avoidance of state.founder.avoidance_patterns.slice(0, 3)) {
    push(
      `You tend to avoid ${avoidance}.`,
      "Derived from repeated skips, overrides, or delays around this category of work.",
      [...state.execution.skipped_actions.slice(0, 2), ...state.execution.delayed_actions.slice(0, 1)].filter(Boolean),
      Math.max(0.25, (state.founder.confidence / 100) * 0.9),
      state.temporal.weakening_patterns.length ? "weakening" : "persistent",
    );
  }

  for (const window of state.founder.operating_windows) {
    push(
      window,
      "Derived from timestamps of your completed vs. dropped activity, not a stated preference.",
      [],
      0.5,
      "emerging",
    );
  }

  return { beliefs: beliefs.slice(0, 8), suppressed: suppressed.slice(0, 4) };
}

function mayBeWrongAbout(state: FounderIntelligenceState, accuracy: IntelligenceAccuracy, asOf: Date): string[] {
  const items: string[] = [];

  if (state.founder.confidence < 40) {
    items.push("There isn't much history yet, so the strengths/avoidance beliefs above are low-confidence and may shift quickly.");
  }
  for (const contradiction of state.strategy.contradictions.slice(0, 2)) {
    items.push(`Possible contradiction it hasn't resolved: ${contradiction}`);
  }
  if (accuracy.sample_size >= 5 && accuracy.average_match_score < 0.4) {
    items.push("Recent recommendations haven't matched what you actually did — its model of what you need next may be stale.");
  }
  // Only still-meaningfully-active corrections (same decay used to weight
  // beliefs above) — a correction from months ago that's fully decayed
  // shouldn't keep resurfacing here as if it were still unresolved.
  const activeCorrections = state.founder.corrections
    .filter((c) => decayedCorrectionWeight(c.created_at, asOf) >= 0.1)
    .slice(-2);
  for (const correction of activeCorrections) {
    items.push(`Founder correction to retain: BuildMind believed "${correction.belief}", but the founder said "${correction.correction}".`);
  }
  if (!items.length) {
    items.push("No unresolved contradictions detected right now; confidence in the beliefs above is as good as it currently gets.");
  }
  return items.slice(0, 4);
}

function accuracySummary(accuracy: IntelligenceAccuracy): string {
  if (!accuracy.sample_size) return "Not enough resolved recommendations yet to self-score accuracy.";
  const pct = Math.round(accuracy.average_match_score * 100);
  const trendText = accuracy.trend === "up" ? "and improving" : accuracy.trend === "down" ? "but slipping" : accuracy.trend === "flat" ? "and holding steady" : "";
  return `Its recommendations have matched what you actually did about ${pct}% of the time over the last ${accuracy.sample_size} resolved recommendations${trendText ? `, ${trendText}` : "."}`;
}

function toMirrorSignals(state: FounderIntelligenceState, asOf: Date): MirrorSignal[] {
  // Same decay + active/expired cutoff buildDecisionState's gating uses —
  // imported, not re-derived, so this section can never quietly disagree
  // with what's actually influencing today's recommendation.
  return activeSignals(state.signals, asOf)
    .filter((s) => s.lifecycle === "active" || s.lifecycle === "acknowledged")
    .slice(0, 8)
    .map((s: IntelligenceSignal & { decayed_confidence: number }) => ({
      id: s.id,
      type: s.type,
      severity: s.severity,
      title: s.title,
      summary: s.summary,
      recommended_response: s.recommended_response,
      evidence: s.evidence.slice(0, 3).map((e) => ({ source: e.source, detail: e.detail })),
      decayed_confidence: Math.round(s.decayed_confidence * 100) / 100,
      lifecycle: s.lifecycle,
    }));
}

function toMirrorDecision(state: FounderIntelligenceState): FounderMirror["decision"] {
  const top = state.decision.top_candidate;
  const alternatives = state.decision.candidates
    .filter((c) => c.id !== top?.id)
    .sort((a, b) => b.scores.total - a.scores.total)
    .slice(0, 3)
    .map((c) => ({
      id: c.id,
      action: c.action,
      rationale: c.rationale,
      score: c.scores.total,
      gap_to_top: top ? Math.max(0, Math.round((top.scores.total - c.scores.total) * 10) / 10) : 0,
    }));
  return {
    top: top
      ? { id: top.id, action: top.action, rationale: top.rationale, why_it_beats_alternatives: top.why_it_beats_alternatives, score: top.scores.total }
      : null,
    alternatives,
  };
}

/**
 * Builds the Founder Mirror from the already-computed FounderIntelligenceState
 * plus the rolling prediction accuracy from the learning loop (Phase 11).
 * Deterministic given the same inputs and the same Math.random draws used by
 * sampleBeta — cheap enough to compute on every page load (Phase 13: model
 * cost control).
 */
export function buildFounderMirror(state: FounderIntelligenceState, accuracy: IntelligenceAccuracy): FounderMirror {
  const asOf = new Date(state.generated_at);
  const { beliefs, suppressed } = beliefsFromState(state, asOf);
  return {
    beliefs,
    skills: buildFounderSkills(state),
    recent_changes: state.founder.recent_changes,
    strengthening_patterns: state.temporal.strengthening_patterns,
    weakening_patterns: state.temporal.weakening_patterns,
    may_be_wrong_about: mayBeWrongAbout(state, accuracy, asOf),
    signals: toMirrorSignals(state, asOf),
    decision: toMirrorDecision(state),
    suppressed_beliefs: suppressed,
    self_reported_accuracy: {
      sample_size: accuracy.sample_size,
      accuracy_pct: accuracy.sample_size ? Math.round(accuracy.average_match_score * 100) : null,
      trend: accuracy.trend,
      summary: accuracySummary(accuracy),
    },
    generated_at: state.generated_at,
  };
      }
