/**
 * lib/recoveryMode.ts — Forgiveness Protocol & Recovery Mode (Playbook §4.2)
 *
 * NEW IN V4. Fixes guilt churn — the #1 retention killer.
 *
 * When Momentum Score has decayed for 3+ consecutive days, the Evening Check
 * shifts into Recovery Mode. The framing is critical: stop the decay with one
 * micro-task, not the big goal. One micro-task generated by the Reflexion loop.
 * Designed to be impossible to say no to.
 *
 * After the Reset Mission is complete, Momentum Score ticks up slightly and
 * full mode resumes the next morning.
 *
 * PRINCIPLE: Founders don't delete apps because they fail. They delete apps to
 * escape the feeling of failure. Recovery Mode removes the escape motive by
 * removing the shame.
 */

import { callModelJSON } from "./ai-providers";
import type { ReflexionContext } from "./reflexion";

export interface RecoveryModeStatus {
  active: boolean;
  triggeredAt?: string;      // ISO date
  daysInDecay: number;
  resetMissionComplete: boolean;
}

export interface ResetMission {
  task: string;              // The micro-task — designed to be doable in 5 minutes
  rationale: string;         // Why this specific micro-task, max 1 sentence
  estimatedMinutes: number;  // Always <= 10
}

// ── Detection ────────────────────────────────────────────────────────────────

/**
 * Determine whether Recovery Mode should activate.
 * Triggers when Momentum Score has decayed for 3+ consecutive days.
 */
export function shouldActivateRecoveryMode(
  daysInactive: number,
  momentumScore: number,
  previousMomentumScore: number
): boolean {
  const isDecaying = momentumScore < previousMomentumScore;
  return daysInactive >= 3 && isDecaying;
}

/**
 * Recovery Mode message shown in the Evening Check instead of the standard nudge.
 * Framing is critical — never shame, always forward.
 */
export function getRecoveryModeMessage(): string {
  return "Let's stop the decay right now with one thing. Not your big goal — something that takes 5 minutes.";
}

// ── Reset Mission Generation ─────────────────────────────────────────────────

/**
 * Generate a micro-task Reset Mission for a founder in Recovery Mode.
 * The task must be designed to be impossible to say no to — under 10 minutes,
 * concretely actionable, tied to their startup context.
 *
 * This is the most important output of Recovery Mode: a task so small that
 * completing it restarts momentum without triggering avoidance.
 */
export async function generateResetMission(
  context: ReflexionContext
): Promise<ResetMission> {
  const prompt = `You are BuildMind's Recovery Mode engine. A founder has been inactive for 3+ days.
Generate a micro-task Reset Mission. Rules:
- The task must be completable in 5 minutes or less
- It must be concrete and actionable (no "think about X")
- It must be tied to their actual startup context
- It must not be their big scary task — it must be the smallest possible re-entry point
- If they're in early stage: something involving one conversation, one search, or one sentence written
- No motivational language. Just the task.

Startup: ${context.startupSummary || "Not yet defined"}
Stage: ${context.stage}
Momentum score: ${context.momentumScore}/100
Avoidance signals: ${context.avoidanceSignals?.join(", ") || "None recorded"}

Return JSON with exactly: { "task": string, "rationale": string, "estimatedMinutes": number }
The rationale must be one sentence max 12 words. estimatedMinutes must be <= 10.`;

  try {
    const parsed = await callModelJSON<Partial<ResetMission>>([
      { role: "system", content: prompt },
      { role: "user", content: "Generate the Reset Mission." },
    ], { role: "reasoning", temperature: 0.4, maxTokens: 200 });

    return {
      task: parsed.task ?? "Send one message to a potential user asking if they've ever experienced [your problem].",
      rationale: parsed.rationale ?? "One conversation is all it takes to restart.",
      estimatedMinutes: Math.min(10, Number(parsed.estimatedMinutes) || 5),
    };
  } catch {
    return {
      task: "Open a notes app and write one sentence: what is the core problem your startup solves?",
      rationale: "Starting small beats not starting at all.",
      estimatedMinutes: 5,
    };
  }
}

// ── Momentum Recovery ────────────────────────────────────────────────────────

/**
 * Momentum bump after a Reset Mission is completed.
 * Small but intentional — enough to signal progress without overstating it.
 */
export function momentumAfterResetMission(current: number): number {
  return Math.min(100, current + 4); // +4: meaningful but not full task credit
}

/**
 * Determine what NOT to show in Recovery Mode.
 * The score in isolation is demotivating. Always show path forward.
 */
export function shouldShowScoreIsolated(recoveryActive: boolean): boolean {
  return !recoveryActive; // Never show score alone during recovery
}
